name = "no-choice-meetup-room"
compatibility_date = "2026-07-04"
pages_build_output_dir = "./public"

[[d1_databases]]
binding = "DB"
database_name = "no-choice-meetup-room"
database_id = "e605507a-d1aa-402b-94e5-64e7f3b24b26"
